config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  resources :topics, only: [:index]
  resources :confirmation_questions, only: [:index]
  post 'confirmation_answers/bulk_update', to: 'confirmation_answers#bulk_update'
  resources :questions
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint           not null, primary key
#  title      :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_questions_on_user_id  (user_id)
#
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @topics = Topic.all.order(:created_at)
    @questions = Question.all.order(:created_at)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :content).merge(user: current_user)
  end
end

app/views/questions/_question.html.erb
<div class="flex p-4">
  <div class="w-24">
    <%= image_tag "no-profile-image.png", class: "img-thumbnail size-16 mx-auto" %>
    <p class="text-sm"><%= "テストユーザー" %></p>
  </div>
  <div class="">
    <%= link_to question_path(question), class: "" do %>
      <h3 class="text-2xl">
        <span class="badge text-bg-danger">未解決</span>
        <%= question.title %>
      </h3>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="flex flex-col min-h-screen w-full">
  <%= render "shared/header" %>
  <main class="flex-grow flex bg-white">
    <%= render "shared/sidebar" %>
    <div class="container flex-grow py-12 px-4 mx-auto">
      <div class="pb-3">
        <%= link_to "質問する", new_question_path, class: "btn btn-primary" %>
      </div>
      <%= form_with url: questions_path, class: "" do |f| %>
        <div class="flex space-x-4">
          <%= f.text_field :keyword, class: "form-control" %>
          <%= f.select :topic_id, options_for_select(@topics.map { |t| [t.name, t.id] }), { include_blank: "トピック" }, class: "form-select" %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
      <% end %>
      <div>
        <%= render @questions %>
      </div>
    </div>
  </main>
  <%= render "shared/footer" %>
</div>

app/views/questions/new.html.erb
<div class="flex flex-col min-h-screen w-full">
  <%= render "shared/header" %>
  <main class="flex-grow flex bg-white">
    <%= render "shared/sidebar" %>
    <div class="container flex-grow py-12 px-4 mx-auto">
      <h2>質問する</h2>
      <!-- エラーメッセージ -->
      <% if @question.errors.any? %>
        <%= @question.errors.count %>件のエラーが発生しました
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @question do |form| %>
        <%= form.text_field :title, placeholder: "タイトル" %>
        <%= form.rich_text_area :content %>
        <%= form.submit "送信", class: "main-button" %>
      <% end %>
    </div>
  </main>
  <%= render "shared/footer" %>
</div>

app/views/questions/show.html.erb
<div class="flex flex-col min-h-screen w-full">
  <%= render "shared/header" %>
  <main class="flex-grow flex bg-white">
    <%= render "shared/sidebar" %>
    <div class="container flex-grow py-12 px-4 mx-auto">
      <div class="flex">
        <div class="profile">
          <div class="flex items-center">
            <p><%= current_user.name %></p>
        </div>
        <div>
          <h3><%= @question.title %></h3>
        </div>
      </div>
    </div>
  </main>
  <%= render "shared/footer" %>
</div>